-- =============================================
-- AGENT EVENTS (audit log of agent actions)
-- =============================================

CREATE TABLE IF NOT EXISTS agent_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_name TEXT NOT NULL,
  event_type TEXT NOT NULL,

  user_id UUID REFERENCES profiles(id),
  entity_id UUID REFERENCES entities(id),

  input_data JSONB,
  output_data JSONB,
  tools_used TEXT[],

  execution_time_ms INTEGER,
  tokens_used INTEGER,
  cost_usd DECIMAL(10,6),

  status TEXT CHECK (status IN ('success', 'failure', 'partial')),
  error_message TEXT,

  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_agent_events_agent ON agent_events(agent_name, created_at DESC);
CREATE INDEX idx_agent_events_user ON agent_events(user_id);
CREATE INDEX idx_agent_events_entity ON agent_events(entity_id);
CREATE INDEX idx_agent_events_status ON agent_events(status) WHERE status = 'failure';
CREATE INDEX idx_agent_events_created ON agent_events(created_at DESC);

-- =============================================
-- INSIGHTS (generated by agents)
-- =============================================

CREATE TABLE IF NOT EXISTS insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id),
  entity_id UUID REFERENCES entities(id),

  type TEXT CHECK (type IN (
    'spending_pattern',
    'saving_opportunity',
    'budget_alert',
    'subscription_optimization',
    'cashflow_forecast',
    'runway_warning',
    'category_trend',
    'merchant_recommendation'
  )),

  title TEXT NOT NULL,
  summary TEXT,
  detailed_analysis JSONB,

  -- Actionable recommendations
  recommendations JSONB,
  potential_impact DECIMAL(12,2),

  -- Relevance
  priority TEXT CHECK (priority IN ('low', 'medium', 'high')),
  expires_at TIMESTAMPTZ,

  -- User interaction
  viewed BOOLEAN DEFAULT FALSE,
  viewed_at TIMESTAMPTZ,
  dismissed BOOLEAN DEFAULT FALSE,
  action_taken TEXT,

  -- Agent metadata
  generated_by TEXT NOT NULL,
  generation_metadata JSONB,

  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_insights_user ON insights(user_id) WHERE NOT dismissed;
CREATE INDEX idx_insights_entity ON insights(entity_id) WHERE NOT dismissed;
CREATE INDEX idx_insights_priority ON insights(priority);
CREATE INDEX idx_insights_type ON insights(type);
CREATE INDEX idx_insights_created ON insights(created_at DESC);

-- =============================================
-- ANOMALIES (detected by Ghost Hunter agent)
-- =============================================

CREATE TABLE IF NOT EXISTS anomalies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_id UUID REFERENCES entities(id),
  user_id UUID REFERENCES profiles(id),

  type TEXT CHECK (type IN (
    'duplicate_subscription',
    'forgotten_vendor',
    'unusual_amount',
    'category_mismatch',
    'duplicate_transaction',
    'missing_receipt',
    'gst_mismatch',
    'budget_overage'
  )),

  severity TEXT CHECK (severity IN ('low', 'medium', 'high', 'critical')),

  title TEXT NOT NULL,
  description TEXT,

  -- Related data
  related_transactions UUID[],
  related_subscriptions UUID[],
  suggested_action TEXT,
  potential_savings DECIMAL(12,2),

  -- Status
  status TEXT DEFAULT 'open' CHECK (status IN ('open', 'investigating', 'resolved', 'dismissed')),
  resolved_by UUID REFERENCES profiles(id),
  resolved_at TIMESTAMPTZ,
  resolution_notes TEXT,

  -- Agent metadata
  detected_by TEXT,
  detection_metadata JSONB,
  confidence DECIMAL(3,2),

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_anomalies_entity ON anomalies(entity_id);
CREATE INDEX idx_anomalies_user ON anomalies(user_id);
CREATE INDEX idx_anomalies_type ON anomalies(type);
CREATE INDEX idx_anomalies_status ON anomalies(status) WHERE status = 'open';
CREATE INDEX idx_anomalies_severity ON anomalies(severity);

-- Add agent_metadata to transactions for tracking
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS agent_metadata JSONB DEFAULT '{}';

-- Row Level Security
ALTER TABLE agent_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE anomalies ENABLE ROW LEVEL SECURITY;

CREATE POLICY agent_events_select_policy ON agent_events
  FOR SELECT USING (
    auth.uid() = user_id OR
    EXISTS (SELECT 1 FROM entity_members WHERE entity_id = agent_events.entity_id AND user_id = auth.uid())
  );

CREATE POLICY insights_select_policy ON insights
  FOR SELECT USING (
    auth.uid() = user_id OR
    EXISTS (SELECT 1 FROM entity_members WHERE entity_id = insights.entity_id AND user_id = auth.uid())
  );

CREATE POLICY anomalies_select_policy ON anomalies
  FOR SELECT USING (
    auth.uid() = user_id OR
    EXISTS (SELECT 1 FROM entity_members WHERE entity_id = anomalies.entity_id AND user_id = auth.uid())
  );

COMMENT ON TABLE agent_events IS 'Audit log of all AI agent executions';
COMMENT ON TABLE insights IS 'AI-generated financial insights and recommendations';
COMMENT ON TABLE anomalies IS 'Detected expense anomalies and wasteful spending';
